[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

build_flags =
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    bblanchon/ArduinoJson
    me-no-dev/ESP Async WebServer
    me-no-dev/AsyncTCP