[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    ESP32Async/ESPAsyncWebServer
    bblanchon/ArduinoJson

upload_speed = 921600